name: NeoHide
version: 1.1.0
main: com.neohide.neohide.NeoHide
api-version: "1.16"
author: NeoStudio

commands:
  neohide:
    description: Main command for NeoHide
    usage: /<command> [help|reload|status|hide|unhide|list|protect|vanish|spy|cmdspy|web]
    permission: neohide.use
    aliases: [nh, hide]

permissions:
  neohide.use:
    description: Allows using NeoHide commands
    default: op
  neohide.reload:
    description: Allows reloading configuration
    default: op
  neohide.manage:
    description: Allows managing hidden commands and permissions
    default: op
  neohide.view:
    description: Allows viewing hidden commands
    default: op
  neohide.alerts:
    description: Receive security alerts
    default: op
  neohide.bypass:
    description: Bypass command hiding
    default: op
  neohide.vanish:
    description: Allows using vanish
    default: op
  neohide.vanish.see:
    description: Can see vanished players
    default: op
  neohide.hide:
    description: Allows hiding from other players
    default: op
  neohide.hide.see:
    description: Can see hidden players
    default: op
  neohide.spy:
    description: Allows spying on players
    default: op
  neohide.spy.commands:
    description: Allows spying on commands
    default: op
  neohide.web:
    description: Access web interface
    default: op